name: idea_version
description: A simple console application.
version: 0.0.1
author: Guenter Zoechbauer <guenter@gzoechbauer.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  xml: '^2.5.0'
  http: '^0.11.3+13'
